# Event study model configuration

# Event study parameters
event_study:
  # Event window configuration
  event_window:
    pre_event_days: 5
    post_event_days: 5
    estimation_window: 250
  
  # Return calculation
  returns:
    method: "log"  # log returns or simple returns
    frequency: "daily"
  
  # Market model parameters
  market_model:
    benchmark: "SPY"  # S&P 500 ETF as market proxy
    risk_free_rate: "DGS3MO"  # 3-month Treasury rate
  
  # Statistical tests
  tests:
    - "parametric"  # t-test
    - "nonparametric"  # Wilcoxon signed-rank test
    - "bootstrap"  # Bootstrap test
  
  # Confidence levels
  confidence_levels: [0.90, 0.95, 0.99]
  
  # Bootstrap parameters
  bootstrap:
    n_samples: 1000
    random_seed: 42

# Buy-and-hold abnormal returns (BHAR)
bhar:
  # Holding periods (in trading days)
  holding_periods: [1, 5, 10, 20, 60]
  
  # Benchmark for BHAR calculation
  benchmark: "SPY"

# Cumulative abnormal returns (CAR)
car:
  # CAR calculation windows
  windows:
    - [0, 1]    # Event day + 1
    - [0, 5]    # Event day + 5
    - [-1, 1]   # Day before to day after
    - [-5, 5]   # 5 days before to 5 days after

# Abnormal volatility
abnormal_volatility:
  # Volatility models
  models:
    - "garch"
    - "egarch"
    - "rolling_window"
  
  # Rolling window for volatility calculation
  rolling_window: 30
  
  # GARCH model parameters
  garch:
    p: 1
    q: 1
    distribution: "normal"

# Event categorization
event_categorization:
  # Categories for policy events
  categories:
    hawkish:
      keywords: ["hawkish", "tightening", "inflation", "rate increase"]
    dovish:
      keywords: ["dovish", "accommodative", "stimulus", "rate cut"]
    neutral:
      keywords: ["neutral", "data dependent", "monitoring"]
  
  # Sentiment thresholds
  sentiment_threshold: 0.5

# Robustness checks
robustness:
  # Alternative estimation windows
  estimation_windows: [200, 250, 300]
  
  # Alternative event windows
  event_windows:
    - [3, 3]   # 3 days before/after
    - [5, 5]   # 5 days before/after
    - [10, 10] # 10 days before/after
  
  # Alternative benchmarks
  benchmarks:
    - "SPY"    # S&P 500
    - "QQQ"    # NASDAQ
    - "IWM"    # Russell 2000
    - "EFA"    # EAFE (international)

# Output configuration
output:
  # Tables to generate
  tables:
    - "summary_statistics"
    - "car_results"
    - "bhar_results"
    - "abnormal_volatility"
    - "robustness_checks"
  
  # Figures to generate
  figures:
    - "car_plot"
    - "bhar_plot"
    - "volatility_plot"
    - "event_timeline"
  
  # File formats
  formats: ["csv", "xlsx", "html"]
